apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-app
  namespace: default
spec:
  dnsNames:
    - dns name . com
  secretName: example-tls-app
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer