apiVersion: v1
kind: Service
metadata:
  name: nfs-server-dke
spec:
  clusterIP: 10.24.4.112
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server-dke