apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-web-pvc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
