apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-pg-pvc
  annotations:
    components.gke.io/layer: addon 
    storageclass.kubernetes.io/is-default-class: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi